export const TRANSLATIONS = {
  vi: {
    // Navbar
    navMatches: "Trận đấu",
    navStandings: "Bảng xếp hạng",
    navNews: "Tin nóng WC",
    navOracle: "Tiên tri AI 🐷",
    navProfile: "Hồ sơ & Ví",
    navLogin: "Đăng nhập",
    navAdminPortal: "Cổng Quản trị Admin Portal",
    withHeoHong: "Cùng Heo Hồng 🐷",

    // MatchList
    scheduleAndScores: "Lịch thi đấu & Tỷ số",
    liveCountText: "{count} Trực tiếp",
    aiTrackRecord: "🤖 HIỆU SUẤT DỰ ĐOÁN AI (TRACK RECORD)",
    eloPoissonModels: "Mô hình ELO & Poisson",
    aiAccuracyText: "Đúng {correct} trên {total} trận đã kết thúc",
    aiAccuracyDesc: "Tỷ lệ chính xác dựa trên dự đoán pre-match trước giờ bóng lăn.",
    groupFilterLabel: "Bảng đấu:",
    allGroupsOption: "Tất cả các bảng (A - L)",
    groupLabel: "Bảng {group}",
    tabAll: "Tất cả",
    tabLive: "Live",
    tabUpcoming: "Sắp đá",
    tabFinished: "Đã xong",
    noMatchesInCategory: "Không có trận đấu nào trong mục này",
    unfollow: "Bỏ theo dõi",
    followMatch: "Theo dõi trận đấu",
    liveText: "Trực tiếp",
    featuredText: "Nổi bật",
    kickoffSchedule: "Lịch thi đấu",
    versusText: "VS",
    aiProbText: "AI: {home}%|{away}%",

    // MatchDetail
    backToList: "Trở về danh sách",
    tabStats: "Thống kê",
    tabLineups: "Đội hình",
    tabTimeline: "Diễn biến",
    tabAiPredictor: "Nhận định AI",
    tabBettingOdds: "Tỷ lệ cược",
    noStatsData: "Chưa có dữ liệu thống kê trực tiếp cho trận đấu này.",
    noLineupsData: "Đội hình dự kiến / ra sân chưa cập nhật.",
    noTimelineData: "Diễn biến trận đấu chưa bắt đầu.",
    aiMatchPredictionTitle: "Dự đoán kết quả (Pre-match AI)",
    winLabel: "Thắng",
    drawLabel: "Hòa",
    modelConfidence: "Độ tin cậy mô hình:",
    tacticalAnalysis: "Phân tích chiến thuật:",
    oddsEuro: "Kèo Châu Âu (1x2)",
    oddsHandicap: "Kèo Chấp (Handicap)",
    oddsOverUnder: "Kèo Tài Xỉu (Over/Under)",
    homeLabel: "Chủ",
    awayLabel: "Khách",
    overLabel: "Tài",
    underLabel: "Xỉu",
    mainHandicap: "Kèo bóng chính",
    totalGoals: "Kèo tổng bàn thắng",
    loginToBet: "Đăng nhập cược",
    liveStatsPossession: "Kiểm soát bóng",
    liveStatsShots: "Tổng số cú sút",
    liveStatsShotsOnTarget: "Sút trúng đích",
    liveStatsFouls: "Phạm lỗi",
    liveStatsCorners: "Phạt góc",
    liveStatsYellowCards: "Thẻ vàng",
    liveStatsRedCards: "Thẻ đỏ",

    // BetSlip
    betSlipTitle: "Phiếu cược vui",
    betPlacedSuccess: "Đặt cược thành công!",
    betTicketId: "Vé cược:",
    closeBetSlip: "Đóng phiếu cược",
    liveBetLabel: "Kèo Trực tiếp",
    stakeLabel: "Xu cược",
    coinMascot: "xu 🐷",
    oddsLabel: "Tỉ lệ cược",
    estReturnLabel: "Nhận lại dự kiến",
    placeBetNow: "Đặt cược ngay",
    emptyBetSlipTitle: "Phiếu cược trống",
    emptyBetSlipDesc: "Chọn bất kỳ nút kèo cược nào trong bảng chi tiết trận đấu để bắt đầu.",
    betHistoryCount: "Lịch sử cược ({count})",
    clearBetHistory: "Xóa lịch sử cược",
    statusPending: "Đang chạy",
    statusWon: "Thắng",
    statusLost: "Thua",
    betHistoryCardDesc: "Vốn: {stake} xu 🐷 • lúc {time}",
    betHistoryPicked: "Bắt:",
    betHistoryReturned: "Nhận về:",
    betHistoryPaid: "Thanh toán:",
    betHistoryEstPayout: "Dự kiến nhận:",
    placingBetLoader: "Đang giao dịch cược...",
    alertMultipleTen: "Số xu cược phải là bội số của 10 (ví dụ: 10, 20, 50, 100...).",
    alertLoginRequired: "Vui lòng đăng nhập bằng Google để thực hiện đặt cược vui!",
    alertInsufficientBalance: "Số dư xu Heo Vàng không đủ để đặt cược vui!",
    confirmClearHistory: "Bạn muốn xóa toàn bộ lịch sử cược?",

    // Profile
    profileWalletTitle: "Hồ sơ Cá nhân & Ví ảo",
    profileWalletDesc: "Đăng nhập bằng tài khoản Google để kích hoạt tính năng lưu trận đấu yêu thích, chọn đội tuyển cưng, và chơi cược vui mô phỏng!",
    logoutBtn: "Đăng xuất",
    subTabWallet: "Ví cược vui",
    subTabWatchlist: "Theo dõi",
    subTabFavorites: "Đội cưng",
    subTabHistory: "Lịch sử cược",
    availableBalance: "Số dư cược vui khả dụng",
    claimFreeCoins: "Nhận lại 10.000 xu Heo Vàng 🐷",
    totalBetsLabel: "Tổng vé cược",
    winRateLabel: "Tỉ lệ thắng",
    wonLostLabel: "Vé Thắng/Thua",
    bookmarkedMatchesCount: "Trận đấu đang theo dõi ({count})",
    noBookmarksDesc: "Chưa theo dõi trận nào. Nhấn biểu tượng sao ở bảng danh sách để theo dõi.",
    favoriteTeamsTitle: "Đội tuyển yêu thích",
    mockBetHistoryCount: "Lịch sử cược vui ({count})",
    noMockBetsPlaced: "Chưa có vé cược nào được đặt.",
    ticketIdLabel: "Mã vé:",
    languageSettingLabel: "Ngôn ngữ / Language",
    vietnameseOption: "Tiếng Việt",
    englishOption: "English",

    // Standings
    standingsTitle: "Bảng xếp hạng World Cup 2026",
    posHeader: "Hạng",
    teamHeader: "Đội bóng",
    mpHeader: "Trận",
    wHeader: "T",
    dHeader: "H",
    lHeader: "B",
    gfHeader: "BT",
    gaHeader: "BB",
    gdHeader: "HS",
    ptsHeader: "Điểm",
    viewFullStandings: "Xem bảng xếp hạng đầy đủ",
    closeFullStandings: "Đóng bảng xếp hạng",

    // NewsHub
    newsTitle: "Tin tức World Cup 2026",
    newsDesc: "Cập nhật nóng hổi các tin tức, bình luận và sự kiện bên lề giải vô địch bóng đá thế giới.",
    readMore: "Đọc thêm",
    minutesAgo: "{count} phút trước",
    hoursAgo: "{count} giờ trước",
    newsLatestTag: "Mới nhất",

    // OracleChat
    oracleChatTitle: "Hỏi Heo Tiên Tri AI",
    chatInputPlaceholder: "Nhập câu hỏi...",
    sendBtn: "Gửi",
    oracleGreeting: "Xin chào! Tôi là Heo Tiên Tri 🐷. Hãy hỏi tôi về nhận định trận đấu, phong độ đội bóng hoặc tỷ lệ cược!",
    oracleMascotAlt: "Mascot tiên tri AI",

    // Login/Modal
    loginGoogleTitle: "Đăng nhập bằng Google",
    loginGoogleDesc: "Chọn tài khoản để tiếp tục với AI Football World Cup 2026",
    useAnotherAccount: "Sử dụng tài khoản khác...",
    chooseLanguageLabel: "Chọn ngôn ngữ hiển thị / Choose Display Language",

    // App homepage / Footer
    bettingLegalWarning: "⚠️ Cảnh báo: Cá độ bóng đá là hành vi vi phạm pháp luật tại Việt Nam. Mọi thông tin về tỷ lệ cược và đặt cược trên trang web này chỉ mang tính chất mô phỏng và giải trí vui vẻ, không có giá trị thực tế hoặc quy đổi.",
    copyrightFooter: "© 2026 FIFA World Cup - Thiết kế Glassmorphism",
    heroHeading: "Trải nghiệm Sự kỳ diệu cùng",
    heroDesc: "Người bạn đồng hành AI dễ thương của bạn cho World Cup 2026. Nhận dự đoán, số liệu thống kê trực tiếp và tham gia dự đoán nhận quà áo Labubu Hồng!",
    predictNowBtn: "Soi kèo ngay",
    heroDescSub: "Đồng hành cùng chú heo tiên tri siêu quậy Heo Hồng để nhận định soi kèo đỉnh cao!",
    wc2026Season: "Mùa giải World Cup 2026",
    askNow: "Hỏi ngay",
    chooseOdds: "Chọn kèo",
    clashWc2026: "Đại chiến WC2026!",
    clashWc2026Desc: "Cùng chú heo Heo Hồng 🐷 nhận định chuẩn xác, bắt trọn từng khoảnh khắc kèo trực tiếp hấp dẫn nhất!",
    giftAndPredictions: "Nhận định & Quà tặng",
    giftPromoDesc: "Tham gia dự đoán tỷ số cùng Heo Hồng nhận ngay phần quà áo đấu Labubu hồng cầu thủ giới hạn cực độc!",
    giftPromoDetail: "Xem chi tiết",
    giftPromoAlert: "Chương trình quà tặng Heo Hồng Labubu đang chuẩn bị ra mắt!"
  },
  en: {
    // Navbar
    navMatches: "Matches",
    navStandings: "Standings",
    navNews: "News Hub",
    navOracle: "AI Oracle 🐷",
    navProfile: "Profile & Wallet",
    navLogin: "Sign In",
    navAdminPortal: "Admin Portal Dashboard",
    withHeoHong: "With Heo Hong 🐷",

    // MatchList
    scheduleAndScores: "Schedule & Scores",
    liveCountText: "{count} Live",
    aiTrackRecord: "🤖 AI PREDICTION ACCURACY (TRACK RECORD)",
    eloPoissonModels: "ELO & Poisson Models",
    aiAccuracyText: "Correct: {correct} out of {total} finished matches",
    aiAccuracyDesc: "Accuracy rate is based on pre-match predictions before kickoff.",
    groupFilterLabel: "Group:",
    allGroupsOption: "All Groups (A - L)",
    groupLabel: "Group {group}",
    tabAll: "All",
    tabLive: "Live",
    tabUpcoming: "Upcoming",
    tabFinished: "Finished",
    noMatchesInCategory: "No matches found in this category",
    unfollow: "Unfollow",
    followMatch: "Follow Match",
    liveText: "Live",
    featuredText: "Featured",
    kickoffSchedule: "Upcoming Kickoff",
    versusText: "VS",
    aiProbText: "AI: {home}%|{away}%",

    // MatchDetail
    backToList: "Back to list",
    tabStats: "Statistics",
    tabLineups: "Lineups",
    tabTimeline: "Timeline",
    tabAiPredictor: "AI Predictor",
    tabBettingOdds: "Betting Odds",
    noStatsData: "Live statistical data is not yet available for this match.",
    noLineupsData: "Probable / official lineups have not been updated yet.",
    noTimelineData: "Match timeline events have not started yet.",
    aiMatchPredictionTitle: "Match Prediction (Pre-match AI)",
    winLabel: "Win",
    drawLabel: "Draw",
    modelConfidence: "Model confidence:",
    tacticalAnalysis: "Tactical analysis:",
    oddsEuro: "European Odds (1x2)",
    oddsHandicap: "Handicap Odds",
    oddsOverUnder: "Over/Under Odds",
    homeLabel: "Home",
    awayLabel: "Away",
    overLabel: "Over",
    underLabel: "Under",
    mainHandicap: "Main Handicap",
    totalGoals: "Total Goals",
    loginToBet: "Sign In to Bet",
    liveStatsPossession: "Possession",
    liveStatsShots: "Total Shots",
    liveStatsShotsOnTarget: "Shots on Target",
    liveStatsFouls: "Fouls",
    liveStatsCorners: "Corner Kicks",
    liveStatsYellowCards: "Yellow Cards",
    liveStatsRedCards: "Red Cards",

    // BetSlip
    betSlipTitle: "Mock Bet Slip",
    betPlacedSuccess: "Bet placed successfully!",
    betTicketId: "Ticket ID:",
    closeBetSlip: "Close Bet Slip",
    liveBetLabel: "Live Bet",
    stakeLabel: "Stake Coins",
    coinMascot: "coins 🐷",
    oddsLabel: "Odds",
    estReturnLabel: "Est. Return",
    placeBetNow: "Place Bet Now",
    emptyBetSlipTitle: "Bet Slip is Empty",
    emptyBetSlipDesc: "Select any betting odds button in the match detail panel to start.",
    betHistoryCount: "Bet History ({count})",
    clearBetHistory: "Clear History",
    statusPending: "Pending",
    statusWon: "Won",
    statusLost: "Lost",
    betHistoryCardDesc: "Stake: {stake} coins 🐷 • at {time}",
    betHistoryPicked: "Picked:",
    betHistoryReturned: "Returned:",
    betHistoryPaid: "Paid:",
    betHistoryEstPayout: "Est. payout:",
    placingBetLoader: "Processing transaction...",
    alertMultipleTen: "Bet stake must be a multiple of 10 (e.g. 10, 20, 50, 100...).",
    alertLoginRequired: "Please sign in with Google to place mock bets!",
    alertInsufficientBalance: "Your Heo Gold balance is insufficient for this mock bet!",
    confirmClearHistory: "Do you want to clear your entire bet history?",

    // Profile
    profileWalletTitle: "User Profile & Virtual Wallet",
    profileWalletDesc: "Sign in with a Google account to activate bookmarks, select favorite teams, and play mock betting!",
    logoutBtn: "Logout",
    subTabWallet: "Mock Wallet",
    subTabWatchlist: "Watchlist",
    subTabFavorites: "Favorites",
    subTabHistory: "Bet History",
    availableBalance: "Available Virtual Balance",
    claimFreeCoins: "Claim 10,000 Heo Gold 🐷",
    totalBetsLabel: "Total Tickets",
    winRateLabel: "Win Rate",
    wonLostLabel: "Won/Lost",
    bookmarkedMatchesCount: "Bookmarked Matches ({count})",
    noBookmarksDesc: "No watched matches. Press the star icon in the match list to follow.",
    favoriteTeamsTitle: "Favorite Teams",
    mockBetHistoryCount: "Mock Bet History ({count})",
    noMockBetsPlaced: "No mock bets placed yet.",
    ticketIdLabel: "Ticket ID:",
    languageSettingLabel: "Ngôn ngữ / Language",
    vietnameseOption: "Tiếng Việt",
    englishOption: "English",

    // Standings
    standingsTitle: "World Cup 2026 Standings",
    posHeader: "Pos",
    teamHeader: "Team",
    mpHeader: "MP",
    wHeader: "W",
    dHeader: "D",
    lHeader: "L",
    gfHeader: "GF",
    gaHeader: "GA",
    gdHeader: "GD",
    ptsHeader: "Pts",
    viewFullStandings: "View Full Standings",
    closeFullStandings: "Close Standings",

    // NewsHub
    newsTitle: "World Cup 2026 News",
    newsDesc: "Live updates, insights, and stories from the FIFA World Cup tournament.",
    readMore: "Read more",
    minutesAgo: "{count}m ago",
    hoursAgo: "{count}h ago",
    newsLatestTag: "Latest",

    // OracleChat
    oracleChatTitle: "Ask Oracle AI Piggy",
    chatInputPlaceholder: "Type a question...",
    sendBtn: "Send",
    oracleGreeting: "Hello! I am Oracle Piggy 🐷. Ask me about match predictions, team form, or betting tips!",
    oracleMascotAlt: "AI Oracle Mascot",

    // Login/Modal
    loginGoogleTitle: "Sign In with Google",
    loginGoogleDesc: "Choose an account to continue with AI Football World Cup 2026",
    useAnotherAccount: "Use another account...",
    chooseLanguageLabel: "Chọn ngôn ngữ hiển thị / Choose Display Language",

    // App homepage / Footer
    bettingLegalWarning: "⚠️ Warning: Soccer betting is illegal in Vietnam. All odds and betting information on this site are for simulation and entertainment purposes only, and have no real-world value.",
    copyrightFooter: "© 2026 FIFA World Cup - Glassmorphism Design",
    heroHeading: "Experience the Magic with",
    heroDesc: "Your cute AI companion for World Cup 2026. Get predictions, live stats, and participate in predictions to win a limited edition Pink Labubu T-shirt!",
    predictNowBtn: "Predict Now",
    heroDescSub: "Accompany the mischievous prophet Piggy to predict top matches!",
    wc2026Season: "World Cup 2026 Season",
    askNow: "Ask Now",
    chooseOdds: "Choose Odds",
    clashWc2026: "WC2026 Clashes!",
    clashWc2026Desc: "Accompany the prophet Piggy 🐷 to get accurate insights and catch every live match moment!",
    giftAndPredictions: "Predictions & Gifts",
    giftPromoDesc: "Predict scores with Heo Hong to win a limited edition Pink Labubu player jersey!",
    giftPromoDetail: "View details",
    giftPromoAlert: "Heo Hong Labubu Gift Program is coming soon!"
  }
};
