export const TRANSLATIONS = {
  vi: {
    // Navbar
    navMatches: "Trận đấu",
    navStandings: "Bảng xếp hạng",
    navNews: "Tin nóng WC",
    navOracle: "Bản đồ tâm linh 🔮",
    navProfile: "Hồ sơ & Ví",
    navLogin: "Đăng nhập",
    navAdminPortal: "Cổng Quản trị Admin Portal",
    withHeoHong: "Cùng Heo Hồng 🐷",

    // MatchList
    scheduleAndScores: "Lịch thi đấu & Tỷ số",
    liveCountText: "{count} Trực tiếp",
    aiTrackRecord: "🤖 HIỆU SUẤT DỰ ĐOÁN AI (TRACK RECORD)",
    eloPoissonModels: "Mô hình ELO & Poisson",
    aiAccuracyText: "Đúng {correct} trên {total} trận đã kết thúc",
    aiAccuracyDesc: "Tỷ lệ chính xác dựa trên dự đoán pre-match trước giờ bóng lăn.",
    groupFilterLabel: "Bảng đấu:",
    allGroupsOption: "Tất cả các bảng (A - L)",
    groupLabel: "Bảng {group}",
    tabAll: "Tất cả",
    tabLive: "Live",
    tabUpcoming: "Sắp đá",
    tabFinished: "Đã xong",
    noMatchesInCategory: "Không có trận đấu nào trong mục này",
    unfollow: "Bỏ theo dõi",
    followMatch: "Theo dõi trận đấu",
    liveText: "Trực tiếp",
    featuredText: "Nổi bật",
    kickoffSchedule: "Lịch thi đấu",
    versusText: "VS",
    aiProbText: "AI: {home}%|{away}%",

    // MatchDetail
    backToList: "Trở về danh sách",
    tabStats: "Thống kê",
    tabLineups: "Đội hình",
    tabTimeline: "Diễn biến",
    tabAiPredictor: "Nhận định AI",
    tabBettingOdds: "Giải mã trận đấu",
    noStatsData: "Chưa có dữ liệu thống kê trực tiếp cho trận đấu này.",
    noLineupsData: "Đội hình dự kiến / ra sân chưa cập nhật.",
    noTimelineData: "Diễn biến trận đấu chưa bắt đầu.",
    aiMatchPredictionTitle: "Dự đoán kết quả (Pre-match AI)",
    winLabel: "Thắng",
    drawLabel: "Hòa",
    modelConfidence: "Độ tin cậy mô hình:",
    tacticalAnalysis: "Phân tích chiến thuật:",
    oddsEuro: "Kèo Châu Âu (1x2)",
    oddsHandicap: "Kèo Chấp (Handicap)",
    oddsOverUnder: "Kèo Tài Xỉu (Over/Under)",
    homeLabel: "Chủ",
    awayLabel: "Khách",
    overLabel: "Tài",
    underLabel: "Xỉu",
    mainHandicap: "Kèo bóng chính",
    totalGoals: "Kèo tổng bàn thắng",
    loginToBet: "Đăng nhập cược",
    liveStatsPossession: "Kiểm soát bóng",
    liveStatsShots: "Tổng số cú sút",
    liveStatsShotsOnTarget: "Sút trúng đích",
    liveStatsFouls: "Phạm lỗi",
    liveStatsCorners: "Phạt góc",
    liveStatsYellowCards: "Thẻ vàng",
    liveStatsRedCards: "Thẻ đỏ",

    // BetSlip
    betSlipTitle: "Gieo quẻ chọn phe 🔮",
    betPlacedSuccess: "Gieo quẻ thành công! 🔮",
    betTicketId: "Quẻ số:",
    closeBetSlip: "Đóng quẻ",
    liveBetLabel: "Quẻ trực tiếp",
    stakeLabel: "Xu dự đoán",
    coinMascot: "xu dự đoán 🐷",
    oddsLabel: "Nhân tố tâm linh (Odds)",
    estReturnLabel: "Thu hoạch dự kiến 🪙",
    placeBetNow: "Đặt niềm tin ngay! 🚀",
    emptyBetSlipTitle: "Chưa chọn phe nào 🐷",
    emptyBetSlipDesc: "Chọn một lựa chọn tâm linh trong phần chi tiết trận đấu để gieo quẻ!",
    betHistoryCount: "Nhật ký gieo quẻ ({count}) 📖",
    clearBetHistory: "Xóa nhật ký gieo quẻ",
    statusPending: "Đang chờ AI phán ⏳",
    statusWon: "Gáy sớm! 🔊",
    statusLost: "Về bờ vui vẻ! 🌊",
    betHistoryCardDesc: "Gieo: {stake} xu • lúc {time}",
    betHistoryPicked: "Chọn cửa:",
    betHistoryReturned: "Thu về:",
    betHistoryPaid: "Điểm nhận:",
    betHistoryEstPayout: "AI phán thắng nhận:",
    placingBetLoader: "Đang lắc mai rùa gieo quẻ... 🐢",
    alertMultipleTen: "Số xu dự đoán phải là bội số của 10 (ví dụ: 10, 20, 50...).",
    alertLoginRequired: "Đăng nhập bằng Google để cùng Heo Hồng gieo quẻ dự đoán vui nhé!",
    alertInsufficientBalance: "Số dư Xu dự đoán của bạn không đủ rồi fen ơi!",
    confirmClearHistory: "Bạn muốn xóa sạch nhật ký gieo quẻ bóng đá?",
    quickBetHeading: "Gieo quẻ bóng đá",
    refilledCoinsAlert: "Số dư xu của bạn đã xuống dưới mức tối thiểu! Heo Hồng 🐷 đã tự động tặng thêm cho bạn 10.000 xu dự đoán miễn phí để tiếp tục vui chơi! 🎉",
    alertErrorPlacingBet: "Có lỗi xảy ra khi gieo quẻ!",

    // Profile
    profileWalletTitle: "Hồ sơ Cá nhân & Bản đồ tâm linh",
    profileWalletDesc: "Đăng nhập bằng tài khoản Google để kích hoạt tính năng lưu trận đấu yêu thích, chọn đội tuyển cưng, và gieo quẻ dự đoán vui vẻ cùng Heo Hồng!",
    logoutBtn: "Đăng xuất",
    subTabWallet: "Ví xu dự đoán",
    subTabWatchlist: "Theo dõi",
    subTabFavorites: "Đội cưng",
    subTabHistory: "Nhật ký gieo quẻ vui",
    availableBalance: "Số dư Xu dự đoán khả dụng",
    claimFreeCoins: "Nhận lại 10.000 xu Heo Vàng 🐷",
    totalBetsLabel: "Tổng lượt gieo quẻ",
    winRateLabel: "Tỉ lệ gáy chuẩn 🔊",
    wonLostLabel: "Quẻ Thắng/Thua",
    bookmarkedMatchesCount: "Trận đấu đang theo dõi ({count})",
    noBookmarksDesc: "Chưa theo dõi trận nào. Nhấn biểu tượng sao ở bảng danh sách để theo dõi.",
    favoriteTeamsTitle: "Đội tuyển yêu thích",
    mockBetHistoryCount: "Nhật ký gieo quẻ vui ({count})",
    noMockBetsPlaced: "Chưa có quẻ nào được gieo cả các fen ơi.",
    ticketIdLabel: "Mã quẻ:",
    languageSettingLabel: "Ngôn ngữ / Language",
    vietnameseOption: "Tiếng Việt",
    englishOption: "English",

    // Standings
    standingsTitle: "Bảng xếp hạng World Cup 2026",
    posHeader: "Hạng",
    teamHeader: "Đội bóng",
    mpHeader: "Trận",
    wHeader: "T",
    dHeader: "H",
    lHeader: "B",
    gfHeader: "BT",
    gaHeader: "BB",
    gdHeader: "HS",
    ptsHeader: "Điểm",
    viewFullStandings: "Xem bảng xếp hạng đầy đủ",
    closeFullStandings: "Đóng bảng xếp hạng",

    // NewsHub
    newsTitle: "Tin tức World Cup 2026",
    newsDesc: "Cập nhật nóng hổi các tin tức, bình luận và sự kiện bên lề giải vô địch bóng đá thế giới.",
    readMore: "Đọc thêm",
    minutesAgo: "{count} phút trước",
    hoursAgo: "{count} giờ trước",
    newsLatestTag: "Mới nhất",

    // OracleChat
    oracleChatTitle: "Đàm đạo cùng Heo Hồng 🐷",
    chatInputPlaceholder: "Nhập câu hỏi...",
    sendBtn: "Gửi",
    oracleGreeting: "Chào các fen! Heo Hồng 🐷 đã sẵn sàng cùng anh em đàm đạo về World Cup 2026 rồi đây. Anh em muốn hỏi gì về giải đấu, nhận định tỉ số hay gieo quẻ bóng đá cúp thế giới nào? 🐷⚽",
    oracleMascotAlt: "Mascot tiên tri AI",
    oracleSuggestionHeader: "Gợi ý câu hỏi nhanh:",
    oracleSubTitle: "Hỏi về tỉ số, chiến thuật, bảng đấu & quà tặng",
    oracleResetConfirm: "Bạn có chắc muốn xoá lịch sử trò chuyện với Heo Hồng?",
    oracleResetTitle: "Xoá lịch sử chat",
    oracleLoadingText: "Heo Hồng đang soi dữ liệu...",
    oracleErrorText: "🐷 Ối các fen ơi, Heo Hồng đang bận nhai hạt ngô nên bị nghẹn rồi! Fen hỏi lại giùm heo nhé! 🌽",
    oraclePlaceholder: "Hỏi Heo Hồng về gieo quẻ, tỉ số, bảng đấu...",

    // Login/Modal
    loginGoogleTitle: "Đăng nhập bằng Google",
    loginGoogleDesc: "Chọn tài khoản để tiếp tục với AI Football World Cup 2026",
    useAnotherAccount: "Sử dụng tài khoản khác...",
    chooseLanguageLabel: "Chọn ngôn ngữ hiển thị / Choose Display Language",

    // App homepage / Footer
    bettingLegalWarning: "⚠️ Tuyên bố miễn trừ trách nhiệm: Trang web sử dụng công nghệ AI để phân tích dữ liệu thống kê bóng đá & mô phỏng mô hình giả lập xác suất nhằm mục đích giải trí và tham khảo thông tin. Chúng tôi sử dụng 'Xu dự đoán' ảo không có giá trị quy đổi tiền mặt. Chúng tôi không tổ chức và không khuyến khích bất kỳ hình thức cá cược nào.",
    copyrightFooter: "© 2026 FIFA World Cup - Thiết kế Glassmorphism",
    heroHeading: "Trải nghiệm Sự kỳ diệu cùng",
    heroDesc: "Người bạn đồng hành AI dễ thương của bạn cho World Cup 2026. Nhận giải mã xác suất, số liệu thống kê trực tiếp và tham gia dự đoán nhận quà áo Labubu Hồng!",
    predictNowBtn: "Giải mã trận đấu ngay",
    heroDescSub: "Đồng hành cùng chú heo tiên tri Heo Hồng để giải mã trận đấu và gieo quẻ xác suất cực chuẩn!",
    wc2026Season: "Mùa giải World Cup 2026",
    askNow: "Hỏi ngay",
    chooseOdds: "Chọn phe",
    clashWc2026: "Đại chiến WC2026!",
    clashWc2026Desc: "Cùng chú heo Heo Hồng 🐷 xem bản đồ tâm linh AI và gieo quẻ chọn phe vui vẻ!",
    giftAndPredictions: "Nhận định & Quà tặng",
    giftPromoDesc: "Gieo quẻ trúng lớn cùng Heo Hồng để rinh ngay phần quà áo đấu Labubu hồng cực hot!",
    giftPromoDetail: "Xem chi tiết",
    giftPromoAlert: "Chương trình quà tặng Heo Hồng Labubu đang chuẩn bị ra mắt!"
  },
  en: {
    // Navbar
    navMatches: "Matches",
    navStandings: "Standings",
    navNews: "News Hub",
    navOracle: "AI Oracle (Spiritual) 🐷",
    navProfile: "Profile & Wallet",
    navLogin: "Sign In",
    navAdminPortal: "Admin Portal Dashboard",
    withHeoHong: "With Heo Hong 🐷",

    // MatchList
    scheduleAndScores: "Schedule & Scores",
    liveCountText: "{count} Live",
    aiTrackRecord: "🤖 AI PREDICTION ACCURACY (TRACK RECORD)",
    eloPoissonModels: "ELO & Poisson Models",
    aiAccuracyText: "Correct: {correct} out of {total} finished matches",
    aiAccuracyDesc: "Accuracy rate is based on pre-match predictions before kickoff.",
    groupFilterLabel: "Group:",
    allGroupsOption: "All Groups (A - L)",
    groupLabel: "Group {group}",
    tabAll: "All",
    tabLive: "Live",
    tabUpcoming: "Upcoming",
    tabFinished: "Finished",
    noMatchesInCategory: "No matches found in this category",
    unfollow: "Unfollow",
    followMatch: "Follow Match",
    liveText: "Live",
    featuredText: "Featured",
    kickoffSchedule: "Upcoming Kickoff",
    versusText: "VS",
    aiProbText: "AI: {home}%|{away}%",

    // MatchDetail
    backToList: "Back to list",
    tabStats: "Statistics",
    tabLineups: "Lineups",
    tabTimeline: "Timeline",
    tabAiPredictor: "AI Predictor",
    tabBettingOdds: "Match Oracle / Probability",
    noStatsData: "Live statistical data is not yet available for this match.",
    noLineupsData: "Probable / official lineups have not been updated yet.",
    noTimelineData: "Match timeline events have not started yet.",
    aiMatchPredictionTitle: "Match Prediction (Pre-match AI)",
    winLabel: "Win",
    drawLabel: "Draw",
    modelConfidence: "Model confidence:",
    tacticalAnalysis: "Tactical analysis:",
    oddsEuro: "European Odds (1x2)",
    oddsHandicap: "Handicap Odds",
    oddsOverUnder: "Over/Under Odds",
    homeLabel: "Home",
    awayLabel: "Away",
    overLabel: "Over",
    underLabel: "Under",
    mainHandicap: "Main Handicap",
    totalGoals: "Total Goals",
    loginToBet: "Sign In to Bet",
    liveStatsPossession: "Possession",
    liveStatsShots: "Total Shots",
    liveStatsShotsOnTarget: "Shots on Target",
    liveStatsFouls: "Fouls",
    liveStatsCorners: "Corner Kicks",
    liveStatsYellowCards: "Yellow Cards",
    liveStatsRedCards: "Red Cards",

    // BetSlip
    betSlipTitle: "Predict & Cast Spell 🔮",
    betPlacedSuccess: "Spell cast successfully! 🔮",
    betTicketId: "Spell ID:",
    closeBetSlip: "Close Spell",
    liveBetLabel: "Live Prediction",
    stakeLabel: "Prediction Coins",
    coinMascot: "coins 🐷",
    oddsLabel: "Spiritual Factor (Odds)",
    estReturnLabel: "Est. Harvest 🪙",
    placeBetNow: "Place Trust Now! 🚀",
    emptyBetSlipTitle: "No Choice Selected 🐷",
    emptyBetSlipDesc: "Select a spiritual option in the match details to cast your spell!",
    betHistoryCount: "Spell Journal ({count}) 📖",
    clearBetHistory: "Clear Spell Journal",
    statusPending: "Awaiting AI ⏳",
    statusWon: "Early brag! 🔊",
    statusLost: "Safe return! 🌊",
    betHistoryCardDesc: "Cast: {stake} coins • at {time}",
    betHistoryPicked: "Picked:",
    betHistoryReturned: "Harvested:",
    betHistoryPaid: "Points paid:",
    betHistoryEstPayout: "Est. payout:",
    placingBetLoader: "Casting spell... 🔮",
    alertMultipleTen: "Prediction stake must be a multiple of 10 (e.g. 10, 20, 50...).",
    alertLoginRequired: "Please sign in with Google to cast mock prediction spells!",
    alertInsufficientBalance: "Your Prediction Coins balance is insufficient for this spell!",
    confirmClearHistory: "Do you want to clear your entire spell history?",
    quickBetHeading: "Soccer Forecast",
    refilledCoinsAlert: "Your coin balance fell below the minimum! Heo Hong 🐷 has automatically gifted you 10,000 free prediction coins to continue having fun! 🎉",
    alertErrorPlacingBet: "Error occurred while casting spell!",

    // Profile
    profileWalletTitle: "User Profile & Spiritual Map",
    profileWalletDesc: "Sign in with a Google account to activate bookmarks, select favorite teams, and play prediction simulator with Heo Hong!",
    logoutBtn: "Logout",
    subTabWallet: "Prediction Coins Wallet",
    subTabWatchlist: "Watchlist",
    subTabFavorites: "Favorites",
    subTabHistory: "Spell Journal",
    availableBalance: "Available Prediction Balance",
    claimFreeCoins: "Claim 10,000 Heo Gold 🐷",
    totalBetsLabel: "Total Spells Cast",
    winRateLabel: "Bragging Accuracy 🔊",
    wonLostLabel: "Spells Won/Lost",
    bookmarkedMatchesCount: "Bookmarked Matches ({count})",
    noBookmarksDesc: "No watched matches. Press the star icon in the match list to follow.",
    favoriteTeamsTitle: "Favorite Teams",
    mockBetHistoryCount: "Spell Journal ({count})",
    noMockBetsPlaced: "No spells cast yet.",
    ticketIdLabel: "Spell ID:",
    languageSettingLabel: "Ngôn ngữ / Language",
    vietnameseOption: "Tiếng Việt",
    englishOption: "English",

    // Standings
    standingsTitle: "World Cup 2026 Standings",
    posHeader: "Pos",
    teamHeader: "Team",
    mpHeader: "MP",
    wHeader: "W",
    dHeader: "D",
    lHeader: "L",
    gfHeader: "GF",
    gaHeader: "GA",
    gdHeader: "GD",
    ptsHeader: "Pts",
    viewFullStandings: "View Full Standings",
    closeFullStandings: "Close Standings",

    // NewsHub
    newsTitle: "World Cup 2026 News",
    newsDesc: "Live updates, insights, and stories from the FIFA World Cup tournament.",
    readMore: "Read more",
    minutesAgo: "{count}m ago",
    hoursAgo: "{count}h ago",
    newsLatestTag: "Latest",

    // OracleChat
    oracleChatTitle: "Chat with Heo Hong 🐷",
    chatInputPlaceholder: "Type a question...",
    sendBtn: "Send",
    oracleGreeting: "Hello fens! Heo Hong 🐷 is ready to discuss World Cup 2026 with you. Ask me about the tournament, score predictions, or cast simulated spells! 🐷⚽",
    oracleMascotAlt: "AI Oracle Mascot",
    oracleSuggestionHeader: "Quick Suggestions:",
    oracleSubTitle: "Ask about scores, tactics, groups & giveaways",
    oracleResetConfirm: "Are you sure you want to clear your chat history with Heo Hong?",
    oracleResetTitle: "Clear chat history",
    oracleLoadingText: "Heo Hong is scanning data...",
    oracleErrorText: "🐷 Oh fens, Heo Hong is choked on corn! Please ask again! 🌽",
    oraclePlaceholder: "Ask Heo Hong about spells, scores, groups...",

    // Login/Modal
    loginGoogleTitle: "Sign In with Google",
    loginGoogleDesc: "Choose an account to continue with AI Football World Cup 2026",
    useAnotherAccount: "Use another account...",
    chooseLanguageLabel: "Chọn ngôn ngữ hiển thị / Choose Display Language",

    // App homepage / Footer
    bettingLegalWarning: "⚠️ Disclaimer: This website uses AI technology to analyze football statistical data and simulate probability models for entertainment and informational reference only. We use virtual 'Prediction Coins' with no real-world cash value. We do not organize or encourage any form of gambling.",
    copyrightFooter: "© 2026 FIFA World Cup - Glassmorphism Design",
    heroHeading: "Experience the Magic with",
    heroDesc: "Your cute AI companion for World Cup 2026. Get probability decodes, live stats, and participate in predictions to win a limited edition Pink Labubu T-shirt!",
    predictNowBtn: "Decode Match Now",
    heroDescSub: "Accompany the mischievous prophet Piggy to decode matches and simulate probabilities!",
    wc2026Season: "World Cup 2026 Season",
    askNow: "Ask Now",
    chooseOdds: "Choose Team",
    clashWc2026: "WC2026 Clashes!",
    clashWc2026Desc: "Accompany the prophet Piggy 🐷 to view AI spiritual maps and choose teams for fun!",
    giftAndPredictions: "Predictions & Gifts",
    giftPromoDesc: "Cast prediction spells with Heo Hong to win a limited edition Pink Labubu player jersey!",
    giftPromoDetail: "View details",
    giftPromoAlert: "Heo Hong Labubu Gift Program is coming soon!"
  }
};
